imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User

fr3d_ldap:
    driver:
        host:                192.168.1.23
#       port:                389    # Optionnel
        username:            alex    # Optionnel
        password:            Serveur,2008    # Optionnel
#       bindRequiresDn:      true   # Optionnel
#       baseDn:              ou=users, dc=host, dc=foo   # Optionnel
#       accountFilterFormat: (&(uid=%s)) # Optionnel. sprintf format %s sera le nom d'utilisateur
#       optReferrals:        false  # Optionnel
#       useSsl:              true   # Active l’utilisation de SSL. Optionnel
#       useStartTls:         true   # Active l’utilisation de TLS. Optionnel
#       accountCanonicalForm: 3 # ACCTNAME_FORM_BACKSLASH cela est nécessaire uniquement si vos utilisateurs doivent se connecter avec quelque chose comme HOST \ User
        accountDomainName: sso.local
        accountDomainNameShort: sso
    user:
        baseDn: ou=users, dc=host, dc=foo
        filter: (&(ObjectClass=Person))
#       usernameAttribute: uid # Optionnel
        attributes:          # Spécifie les attributs de mapping ldap [ldap attribut, méthode de l’objet utilisateur]
            - { ldap_attr: uid,  user_method: setUsername }
            #- { ldap_attr: mail, user_method: setEmail }

#           - { ldap_attr: ...,  user_method: ... }         # Optionnel
#   service:
#       user_hydrator: fr3d_ldap.user_hydrator.default # Surchage le user_hydrator par défaut
#       ldap_manager: fr3d_ldap.ldap_manager.default   # Surcharge le ldap_manager par défaut
#       ldap_driver: fr3d_ldap.ldap_driver.zend        # Surcharge le ldap_driver par défaut